"""
Custom exceptions

The final `run()` funtion captures all 

"""

class CleaningError(Exception):
    pass
